### ISSUE TITLE
uniGUI version

### ISSUE THREAD

**Issue by fredycc** [mauriziodm/iORM#14]
What would be the correct uniGUI version to avoid runtime exceptions with demos?

> Error reading UniDBGrid1.Columns: Error reading TUniDBDesktopGridColumn.Expanded: Property Expanded does not exist.

Thank you

**Comment by mauriziodm** [comment]
Hi, examples of iORM were made with uniGUI 1.0.0.1390 RC.
Have a good day.


Maurizio Del Magno
Levante Software

2018-03-03 0:32 GMT+01:00 fredycc <notifications@github.com>:
