### ISSUE TITLE
can support mysql?

### ISSUE THREAD

**Issue by yonghumeijj** [mauriziodm/iORM#31]
can support mysql?

**Comment by mauriziodm** [comment]
Hi, MySQL is not supported at the moment, it wouldn't be hard to do but it
is not planned any time soon.
However, if someone wants to contribute to the project, he is welcome.
Thanks for your interest in this project.
Have a nice day.

Maurizio Del Magno
Levante Software


Il giorno dom 8 gen 2023 alle ore 17:24 小宝软件 ***@***.***> ha
scritto:
